apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routemee-web
  namespace: argocd
spec:
  destination: 
    server: https://kubernetes.default.svc
    namespace: routemee-app
  syncPolicy:
    syncOptions:
      - "CreateNamespace=true"
    
    automated:
      selfHeal: true
      prune: true
    
  project: default
  source:
    repoURL: https://github.com/AliciaC07/Argocd-routemee.git
    targetRevision: HEAD
    path: dev