version: "3"
services:
  # Frontend Service 
  frontend:
    container_name: routemee-frontend
    image: waterpolord/routemee-frontend
    environment:
      API_URL: http://routemee.com:9000
      URL: routemee.com
      HTTPS_METHOD: noredirect
      APP_PORT: 80
      CORS: "false"
    ports:
      - "81:80"
    networks:
      - red
    stdin_open: true
    depends_on:
      - backend
    labels:
      kompose.service.type: LoadBalancer
  # App backend service
  backend:
    container_name: routemee-backend
    image: waterpolord/routemee-backend
    ports:
      - "9000:9000"
    network_mode: "host"
    environment:
      DATABASE_NAME: prueba_perdomo
      DATABASE_PORT: 3730
      APP_PORT: 9000
      
networks:
  red:
    driver: bridge