apiVersion: v1
kind: Service
metadata:
  name: routemee-frontend
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
      nodePort: 31961
    - name: "https"
      port: 443
      targetPort: 8080
      nodePort: 31808
  selector:
    app: routemee-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
