apiVersion: v1
kind: Service
metadata:
  name: routemee-frontend
spec:
  ports:
    - name: "http"
      port: 3033
      targetPort: 80
      nodePort: 31961
  selector:
    app: routemee
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
