apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: frontend-tcp
  name: frontend-tcp
spec:
  ports:
    - name: "81"
      port: 80
      targetPort: 8081
  selector:
    io.kompose.service: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
